### ISSUE TITLE
DllFileNotFound when in used in Xamarin.Forms

### ISSUE THREAD

**Issue by Lelelo1** [rjamesnw/v8dotnet#29]
I get `DllFileNotFound` exeption when using v8.net in a net standard library from a Xamarin Forms project. It happens on both Android and iOS. It could be more of a Xamarin problem as I believe that neither the iOS nor the Android can directly use dll.

I have both dlls in my net standard library project set as `Content`, in Visual Studio.

Looking in the extensive [docs](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/) it says it should be possible. It seems an iOS and Android project has to be added in addition to the netstandardlibrary.

**Comment by tombatron** [comment]
Currently for this project there are only V8 binaries compiled for Windows. You'd have to build the V8 proxy library for the platforms that you're targeting for this to work.

**Comment by Lelelo1** [comment]
So I a would have to set up my machine like the following: https://github.com/rjamesnw/v8dotnet/tree/master/Source/V8.NET-Proxy/V8

Then add `<TargetFrameworks>netstandard2.0;net461;Xamarin.iOS10</TargetFrameworks>` like so to the `V8.Net-Standard.csproj` file. And build `V8.Net-Standard`?

**Comment by tombatron** [comment]
No, you'd have to build: https://github.com/rjamesnw/v8dotnet/tree/master/Source/V8.NET-Proxy

For the platform that you're targeting.

**Comment by rjamesnw** [comment]
Hi, not sure why I didn't get an email about your post. It seems Github sends out notices when it feels like it half the time. :/

@tombatron is correct. Years ago I had to build the V8 source from scratch, so that's what I still do at the moment.  You would have to build the V8 source yourself to target other platforms (like Linux, Mac, etc.).  You also would have to build the C++ wrapper source files that V8.Net uses to interface with Google's V8 libraries.  V8.Net simply P/Invokes to the C++ wrapper to control the V8 libraries.  It does not do much else.  The goal was only to make interfacing from .Net more convenient, staying true (mostly) to how the V8 engine functions and objects work.
