### ISSUE TITLE
Unity/Android Build?

### ISSUE THREAD

**Issue by KTRosenberg** [rjamesnw/v8dotnet#30]
I’m interested in running ES6 Javascript modules within Unity (C#) in a way that lets me call C# functions / pass parameters back and forth. Specifically I’m targeting Android, not Windows. (That’s why something like Clearscript that uses mixed assemblies doesn’t work.) However, I can’t seem to find evidence that V8.NET supports platforms other than Windows. Is what I am looking for possible, and in that case, how would I build the project for my use case?
I’m currently looking around here, but am not really sure how to proceed: https://github.com/rjamesnw/v8dotnet/tree/master/Source/V8.NET-Proxy

**Comment by rjamesnw** [comment]
Hi, not sure why I didn't get an email about your post.  It seems Github sends out notices when it feels like it half the time.  :/

V8.Net uses a native P/Invoke to the underlying native libraries. Currently only the windows libraries are supported, but since the wrapper is pure C#, with some C++ wrappers also, others have ported it to mono in the past successfully. It should be possible to use it for Unity when targeting windows, but not mobile devices, unless you build the V8 libraries for that yourself.  The underlying V8 code is C++, so where that can be ported to should be possible.
