### ISSUE TITLE
Can't set value for list of objects

### ISSUE THREAD

**Issue by mithrey** [rjamesnw/v8dotnet#31]
Hey. I'm trying to set value of list array, but
> Uncaught Error: => Message: Types.ChangeType(): Cannot convert value "[object Layer]" (type: 'System.String') to type 'V8.NET.Console.ObjectExamples.Layer[]'. If you are developing the source type yourself, implement the 'IConvertible' interface. 

Why does V8.Net think this is a string? Is there any way i can execute js correctly?

Here is my code

`public class Layer 
    {
        public string name { get; set; }
    }

    public class Selection 
    {
        public int length => layers.Count;
        public List<Layer> layers;
        public Selection()
        {
            layers = new List<Layer> { new Layer() { name = "ONE" }, new Layer() { name = "TWO" } };
        }
    }
    public class Console
    {
        public void log(string t) { System.Console.WriteLine(t); }
    }

    class Program
    {
        static void Main(string[] args)
        {
            V8Engine v8Engine = new V8Engine();
            v8Engine.GlobalObject.SetProperty("console", new Console(), recursive: true, memberSecurity: ScriptMemberSecurity.ReadWrite);

            v8Engine.RegisterType<Selection>("Selection", true, ScriptMemberSecurity.ReadWrite);
            v8Engine.GlobalObject.SetProperty(typeof(Selection));

            v8Engine.RegisterType<Layer>("Layer", true, ScriptMemberSecurity.ReadWrite); 
            v8Engine.GlobalObject.SetProperty(typeof(Layer));
            v8Engine.RegisterType<Layer[]>();

            v8Engine.RegisterType<System.Collections.Generic.List<Layer>>(null, true, ScriptMemberSecurity.ReadWrite); 
            v8Engine.GlobalObject.SetProperty(typeof(System.Collections.Generic.List<Layer>));
            v8Engine.RegisterType<System.Collections.ArrayList>(null, true, ScriptMemberSecurity.ReadWrite);
            v8Engine.GlobalObject.SetProperty(typeof(System.Collections.ArrayList));

            var gs2 = v8Engine.Execute(
                @"
                    var selection = new Selection();
                    var layer = new Layer();
                    console.log(selection.layers[0].name);
                    selection.layers = [layer];
                    console.log(selection.layers.name);
                   "
            );
            System.Console.WriteLine(gs2.AsString);
            System.Console.ReadKey(true);
        }
    }`

I tried to change layers type to Layer[], but except for this error, engine also returns
> Uncaught Error: The ObjectBinder is missing for property 'name' (name).

then i try to get array element property;

`var selection = new Selection();   
console.log(selection.layers[0].name);`

**Comment by rjamesnw** [comment]
You cannot set a `List<T>` with a JavaScript array.  The V8.Net wrapper is a simple wrapper only, and not meant to convert implicitly in every case.  Trying to set that with a JS array simply fails because the value of the JS array handle in the system just converts to a string value "[object Layer]" (an array showing one object of type Layer).  If you executed `selection.layers = [layer, layer];` you would have seen `Cannot convert value "[object Layer],[object Layer]"`. The array is getting converted into a list of types within it.

When working with the CLR side, you need to think CLR, NOT JS. ;)  The point of registering types involved is to allow JS to create those types.  First thing to learn with this wrapper is that types called without `new` return an instance representing a CLR wrapped value of the specified type; for example:

A primitive wrapped type (convert the number to a specific CLR type):
```
> i = Int32(123)

<object: Object, Active; tracked handle (0), Engine ID: 0, Handle ID: 773, Object ID: -1525, Locked: False>

> dump(i)

* [object Object].$__Type = (System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
* [object Object].$__TypeID = (26)
* [object Object].$__Value = (123)
```
Or with a null value of the list type:
 ```
> l = List$1()

<object: Object, Active; tracked handle (0), Engine ID: 0, Handle ID: 768, Object ID: -1522, Locked: False>

> dump(l)

* [object Object].$__Type = (System.Collections.Generic.List`1[[Layer, V8.Net.Console, Version=1.0.0.65, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
* [object Object].$__TypeID = (11)
* [object Object].$__Value = (undefined)
```

Here is a contrived example of calling and passing CLR methods/types:
```
r = Enumerable.Range(1,Int32('10'));
<Object Binder: Active; tracked handle (0), System.Linq.Enumerable+<RangeIterator>d__113, Engine ID: 0, Handle ID: 762, Object ID: 380, Locked: False>
a = System.String.Join$1([Int32], ', ', r);
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
```
*(that last one above is from the console example project)*

Notice `Join$1([Int32], `? When calling generic methods, you need to include an array of types.  That was the only way I found to simulate the CLR in the JS world. ;)

Currently, when registering generic types in JS I added the number of expected types. So, `List<Layer>` becomes `List$1`, where a Layer object is expected behind the scenes. Executing `List$1.valueOf()` in this case would give:

```
<Type Binder: Active; tracked handle (0), System.Collections.Generic.List`1[[Layer, V8.Net.Console, Version=1.0.0.65, Culture=neutral, PublicKeyToken=null]], Engine ID: 0, Handle ID: 129, Object ID: 64, Locked: False>`
```

However, that also means that if you registered `List<Int32>` right after, you would overwrite the previous one.  For that, you need to simply name them yourself, such as:
```
        v8Engine.GlobalObject.SetProperty(typeof(System.Collections.Generic.List<Layer>), className: "List_Layer");
        v8Engine.GlobalObject.SetProperty(typeof(System.Collections.Generic.List<Int32>), className: "List_Int");

```

The only thing I didn't do - at least not yet - is to allow passing an array of types when create generic types. Creating the default `List$1` is probably not a good idea if you plan to have more, so just rename it properly.

Thinking CLR, not JS, the solution would be:

```
        v8Engine.GlobalObject.SetProperty("console", new CustomConsole(), recursive: true, memberSecurity: ScriptMemberSecurity.ReadWrite);

        v8Engine.RegisterType<Selection>("Selection", true, ScriptMemberSecurity.ReadWrite);
        v8Engine.GlobalObject.SetProperty(typeof(Selection));

        v8Engine.RegisterType<Layer>("Layer", true, ScriptMemberSecurity.ReadWrite);
        v8Engine.GlobalObject.SetProperty(typeof(Layer));
        //v8Engine.RegisterType<Layer[]>();

        v8Engine.RegisterType<System.Collections.Generic.List<Layer>>(null, true, ScriptMemberSecurity.ReadWrite);
        v8Engine.GlobalObject.SetProperty(typeof(System.Collections.Generic.List<Layer>), className: "List_Layer");
        v8Engine.RegisterType<System.Collections.ArrayList>(null, true, ScriptMemberSecurity.ReadWrite);
        v8Engine.GlobalObject.SetProperty(typeof(System.Collections.ArrayList));

        var gs2 = v8Engine.Execute(
            @"
                var selection = new Selection();
                var layer = new Layer();
                console.log(selection.layers[0].name);
                var newList = new List_Layer();
                newList.Add(layer);
                selection.layers = newList;
                console.log(selection.layers[0].name);
               "
        );
        if (gs2.IsError)
            System.Console.WriteLine("Error Message: " + gs2.AsString);
        System.Console.ReadKey(true);
```

I wish I had more time to create better docs, but some of this is covered in the example console when you execute `\init`. ;)
