### ISSUE TITLE
extending .NET type in JS doesn't seem to work

### ISSUE THREAD

**Issue by vvuk** [rjamesnw/v8dotnet#6]
(development branch)  Not quite sure what I'm doing wrong here -- also entirely possible that I'm just missing something and this isn't quite supposed to work :)

I would like to have a class defined in C#, and then give JS the ability to extend that, overriding native methods with JS methods as needed.

Here's my testcase:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using V8.Net;

namespace Test2 {
    class GlobalUtils {
        public static void WriteLine(string s) { Console.WriteLine(s); }
    }

    public class BaseClass {
        public BaseClass() { }
        public void Foo() { Console.WriteLine("BaseClass::Foo"); }
        public void Bar() { Console.WriteLine("BaseClass::Bar"); }
    }

    class Program {
        public static void MainFunc(string[] args) {
            var js = new V8Engine();
            
            js.RegisterType<GlobalUtils>("utils", false, ScriptMemberSecurity.Locked);
            js.GlobalObject.SetProperty(typeof(GlobalUtils));

            js.RegisterType<BaseClass>(null, false, ScriptMemberSecurity.Locked);
            js.GlobalObject.SetProperty(typeof(BaseClass));

            js.ConsoleExecute(jssrc);
        }

        private static string jssrc = @"
function Derived() {
}

Derived.prototype = Object.create(BaseClass.prototype);
Derived.prototype.constructor = Derived;
Derived.prototype.Foo = function() {
    utils.WriteLine('proper foo');
}
Derived.prototype.NewFunc = function() {
    utils.WriteLine('newfunc');
}

var x = new Derived();
x.Foo();
x.Bar();
x.NewFunc();
";
    }
}
```

This results in:

```
C:/proj/cs/ScriptBridge/bin/Debug/ScriptBridge.exe
proper foo
Uncaught TypeError: x.Bar is not a function
  Line: 16  Column: 2
  Stack:
    at V8.NET:16:3
```

as if it's not chaining up to BaseClass at all.  If I create a new instance of `BaseClass`, I can call `Foo` and `Bar` just fine.

Note that if I switch the JS to es6 class syntax, the behaviour changes to the exact opposite: (replace the JS source with this)
```js
class Derived extends BaseClass {
    constructor() { super(); utils.WriteLine('derived constructor'); }
    Foo() { utils.WriteLine('proper foo'); }
    NewFunc() { utils.WriteLine('newfunc'); }
}

var x = new Derived();
x.Foo();
x.Bar();
x.NewFunc();
```
output:
```
derived constructor
BaseClass::Foo
BaseClass::Bar
Uncaught TypeError: x.NewFunc is not a function
  Line: 11  Column: 2
  Stack:
    at V8.NET:11:3
```
In this case, it's as if the `Derived` class just isn't there, and a `BaseClass` was constructed instead -- but the derived constructor is clearly being called.

Also unexpected with the es6 syntax -- `x instanceof Derived` is false, as is `x instanceof BaseClass`.  They're both properly true when using the original prototype-based code.

**Comment by rjamesnw** [comment]
First thing, the type `BaseClass` is bound such that interceptors exist to capture property reads on an INSTANCE of `BaseClass`, and NOT the prototype. ;)  V8 has the notion of FunctionTemplates, and these are used to wrap the types. The function object returned from the function template has a *separate* prototype for the function object, but that has nothing to do with the binding.  The only way to do what you want is this:

`Derived.prototype = Object.create(new BaseClass());`

Then the prototype instance of `BaseClass` will have interceptors to read the .Net instance methods.

This actually poses an interesting design change.  In retrospect, perhaps I can instead create interceptors on the FunctionTemplate's PrototypeTemplate.  Something I'll look into.

**Comment by rjamesnw** [comment]
There is another issue I just noticed aside from all this.  When you call `new BaseClass()`, the interceptor on the V8 object calls into the CLR and creates a BOUND CLR instance with a object tracking ID for the new CLR instance.  This DOES NOT EXIST if you create the instance using a function NOT BOUND (i.e. from within JS).  For example, calling `new Derived()` has NO binding associated, since you constructed it in JS.  As such, the CLR bindings have no way to be triggered, and you will get an error `The ObjectBinder is missing for function 'Foo' (Foo).`. You can tell if there is a valid object as the object ID will be >=1.  If I type `x` I see this now:

`<object: Object, Engine ID: 0, Handle ID: 16, Object ID: -32, Locked: False>`

Object ID -32 means there is no associated CLR object (and thus no binding object in this case).  If I type `new BaseClass()` I get this instead:

`<Object Binder: V8.Net.BaseClass, Engine ID: 0, Handle ID: 18, Object ID: 7, Locked: False>`

Object ID 7, which looked up on the CLR side, points to a binder object for the CLR instance. In fact, it's clearly stated in the output ('Object Binder:') to show the difference between the two. ;)

**Comment by rjamesnw** [comment]
I looked into your code a bit more, I can work around this a bit by doing this:

 ```
  class GlobalUtils
        {
            public static void WriteLine(string s) { Console.WriteLine(s); }
        }

        public class BaseClass
        {
            public BaseClass() { }
            public void Foo() { Console.WriteLine("BaseClass::Foo"); }
            public void Bar() { Console.WriteLine("BaseClass::Bar"); }
        }

        class Program
        {
            public static void MainFunc(V8Engine js, string[] args)
            {
                js.RegisterType<GlobalUtils>("utils", false, ScriptMemberSecurity.Locked);
                js.GlobalObject.SetProperty(typeof(GlobalUtils));

                js.RegisterType<BaseClass>(null, false, ScriptMemberSecurity.ReadWrite);
                js.GlobalObject.SetProperty(typeof(BaseClass));

                js.ConsoleExecute(jssrc);
            }

            private static string jssrc = @"
function Derived() { }

Derived.prototype = Object.create(new BaseClass());
Derived.prototype.constructor = Derived;
Derived.prototype.Foo = function() {
    Derived.prototype.__proto__.Foo();
}
Derived.prototype.Bar = function() {
    Derived.prototype.__proto__.Foo();
}
Derived.prototype.NewFunc = function() {
    utils.WriteLine('newfunc');
}

var x = new Derived();
x.Foo();
x.Bar();
x.NewFunc();
";
        }
```

Note the change here: 

`js.RegisterType<BaseClass>(null, false, ScriptMemberSecurity.ReadWrite);`

You won't be able to set properties on the `Derived` type to override the base prototype otherwise (just the way V8 works with member security). This works because the `Derived.prototype.__proto__` object is associated with a CLR binder (call back hooks [interceptors]).

**Comment by vvuk** [comment]
Ah ha, thanks for the detailed info!  I've moved to a different approach for my project so this isn't as pressing, though I wonder if you could create a Binder object from the JS side when an object is constructed via JS -- you can already detect when the constructor is called, so should be able to do the work on the C# side there.

**Comment by rjamesnw** [comment]
Sorry, not possible. There's no way for me to intercept object creation in JS in V8. But that said, keep in mind derived types in JS usually make some sort of call to the "super" type to initialize properties for the same reason - super types also don't automatically trigger a call to the constructor function, you have to call them explicitly (like the super() call in TypeScript). In the same way, inheriting from a CLR type in JS will require calling something, and that is what I think is the only option - I would have to make a callable CLR bound function on the CLR type to "complete the inheritance" process somehow. ;)

**Comment by vvuk** [comment]
Sorry, that's what I meant - I think it's totally valid to say that you
must call the superclass constructor if you want to inherit from a C# type.
That call can do the appropriate setup.
